/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.uthark.gradle.plugin.golang

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'io.github.uthark.gradle.plugin.golang' plugin.
 */
class GradleGolangPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("io.github.uthark.gradle.plugin.golang")

        // Verify the result
        assertNotNull(project.tasks.findByName("golang"))
    }
}
