/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.uthark.gradle.plugin.golang

import org.gradle.testkit.runner.GradleRunner
import org.junit.Rule
import org.junit.rules.TemporaryFolder
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'io.github.uthark.gradle.plugin.golang' plugin.
 */
class GradleGolangPluginFunctionalTest {
    @get:Rule
    val tempFolder = TemporaryFolder()

    private fun getProjectDir() = tempFolder.root
    private fun getBuildFile() = getProjectDir().resolve("build.gradle")
    private fun getSettingsFile() = getProjectDir().resolve("settings.gradle")

    @Test
    fun `can run task`() {
        // Setup the test build
        getSettingsFile().writeText("")
        getBuildFile().writeText(
            """
plugins {
    id('io.github.uthark.gradle.plugin.golang')
}
"""
        )

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("golang")
        runner.withProjectDir(getProjectDir())
        val result = runner.build();

        // Verify the result
        assertTrue(result.output.contains("Hello from plugin 'io.github.uthark.gradle.plugin.golang'"))
    }
}
