/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.uthark.gradle.plugin.golang

import io.github.uthark.gradle.plugin.golang.task.GoRun
import org.gradle.api.NamedDomainObjectContainer
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.model.ObjectFactory

/**
 * A simple 'hello world' plugin.
 */
class GradleGolangPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        val extension = project.extensions.create("golang", GolangExtension::class.java)
        project.task("configureGoRun") {
            println("configuring go run")
            project.tasks.register("goRun", GoRun::class.java) { task ->
                task.pkg = extension.pkg.get()
            }
        }
    }
}
